spring.datasource.username=neondb_owner
spring.datasource.password=npg_rWUuH0xz9Cky
spring.datasource.url=jdbc:postgresql://ep-rough-term-asehc0ow-pooler.c-4.eu-central-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_rWUuH0xz9Cky&sslmode=require&channelBinding=require