spring.datasource.url=jdbc:postgresql://ep-rough-term-asehc0ow-pooler.c-4.eu-central-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_rWUuH0xz9Cky
spring.jpa.open-in-view=false